version: 2.1
jobs:
  build:
    docker:
      - image: golang:1.16
    steps:
      - checkout
      - restore_cache:
          key: likecoin-chain-{{ checksum "go.mod" }}-{{ checksum "go.sum" }}
      - run:
          name: Dependencies
          command: go mod download
      - save_cache:
          key: likecoin-chain-{{ checksum "go.mod" }}-{{ checksum "go.sum" }}
          paths:
            - /go/pkg
      - run:
          name: Build
          command: go build ./...
      - run:
          name: Test
          command: go test ./...
